---
name: 🐛 Bug
about: 버그를 제보하고 수정이 필요할 때 사용하세요.
title: "[🐛 Bug] "
labels: ["🐛 Bug"]
---
## ❗️ Issue

<!-- 어떤 문제가 발생했는지 구체적으로 작성해 주세요. -->
---
## ✅ How to Reproduce

<!-- 어떤 상황에서 문제가 발생했는지 재현 과정을 단계별로 작성해 주세요. -->
---
## 📷 Screenshots (선택)

<!-- 문제 상황을 보여주는 스크린샷이 있다면 첨부해 주세요. -->
---
## 📒 Remarks

<!-- 추가적으로 전달하거나 메모해 둘 내용이 있다면 적어주세요. -->
