---
name: 🎨 HTML & CSS
about: 마크업 및 스타일 관련 작업이 필요할 때 사용하세요.
title: "[🎨 HTML & CSS] "
labels: ["🎨 HTML & CSS"]
---
## 🎯 목표

<!-- 작업하고자 하는 마크업 또는 스타일 요소를 설명해 주세요. -->
---
## 💡 참고 디자인 / 요구사항

<!-- 참고할 디자인 시안이나 구체적 요구사항이 있다면 작성해 주세요. -->
---
## 📒 Remarks

<!-- 추가로 전달할 메모가 있다면 자유롭게 작성해 주세요. -->
