---
name: 🔁 Refactor
about: 코드 구조 개선이나 리팩터링이 필요한 경우 사용하세요.
title: "[🔁 Refactor] "
labels: ["🔁 Refactor"]
---
## ✏️ 리팩터링 대상

<!-- 리팩터링하고자 하는 코드 또는 컴포넌트를 명확히 작성해 주세요. -->
---
## 📋 개선 방향

<!-- 어떤 부분을 어떻게 리팩터링할 예정인지 간단히 작성해 주세요. -->
---
## 📒 Remarks

<!-- 의논하거나 메모하고 싶은 사항이 있다면 작성해 주세요. -->
