---
name: ⚙️ Setting
about: 프로젝트 설정 관련 변경 사항을 기록할 때 사용하세요.
title: "[⚙️ Setting] "
labels: ["⚙️ Setting"]
---
## 🔧 변경 대상

<!-- 설정하고자 하는 도구, 라이브러리 등을 명확히 작성해 주세요. -->
---
## 📦 작업 내역

<!-- 어떤 설정을 추가/수정/삭제할 계획인지 작성해 주세요. -->
---
## 📒 Remarks

<!-- 관련 문서나 참고한 설정 링크 등 메모가 있다면 적어주세요. -->
