name: ⚙️ Setting
description: 프로젝트 설정 관련 변경 사항을 기록할 때 사용하세요.
title: "[⚙️ Setting] "
labels: ["⚙️ Setting"]
body:
  - type: textarea
    id: target
    attributes:
      label: 🔧 변경 대상
      description: 설정하고자 하는 도구, 라이브러리 등을 명확히 작성해 주세요.
      placeholder: |
        예: ESLint 설정, Tailwind 플러그인 추가 등
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: 📦 작업 내역
      description: 어떤 설정을 추가/수정/삭제할 계획인지 작성해 주세요.
      placeholder: |
        예: tailwind.config.js에 새로운 컬러 팔레트 추가
    validations:
      required: true

  - type: textarea
    id: remarks
    attributes:
      label: 📒 Remarks
      description: 관련 문서나 참고한 설정 링크 등 메모가 있다면 적어주세요.
      validations:
        required: false
